services:
  chromadb:
    image: chromadb/chroma:0.5.23
    container_name: chroma_db
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma/
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma/

volumes:
  chroma_data:
