
app.gemini.api.key=${GEMINI_API_KEY}
# ChromaDB Configuration
chromadb.url=${CHROMA_DB_URL}
chromadb.collection.default-name=${DEFAULT_NAME}
chromadb.collection.llm-name=${LLM_NAME}
gemini.embedding.model.name=${GEMINI_MODEL_NAME}


#testing
spring.servlet.multipart.max-file-size=70MB
spring.servlet.multipart.max-request-size=70MB
