
# Spring AI OpenAI Configuration (Proxying Gemini API)
spring.ai.openai.api-key=${GEMINI_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai
spring.ai.openai.chat.options.model=gemini-2.5-flash
spring.ai.openai.embedding.options.model=gemini-embedding-001

# ChromaDB Configuration (used in custom config to create two vector stores)
chromadb.url=${CHROMA_DB_URL}
chromadb.collection.default-name=${DEFAULT_NAME}
chromadb.collection.llm-name=${LLM_NAME}

# Testing multipart config
spring.servlet.multipart.max-file-size=70MB
spring.servlet.multipart.max-request-size=70MB
