
app.gemini.api.key=${GEMINI_API_KEY}
# ChromaDB Configuration
chromadb.url=${CHROMA_DB_URL}
chromadb.collection.default-name=hybrid_rag_default_collection
chromadb.collection.llm-name=hybrid_rag_llm_collection
gemini.embedding.model.name=${GEMINI_MODEL_NAME}